import type { AwsServiceDef } from "./types.js";

export const AWS_SERVICES: AwsServiceDef[] = [
  {
    id: "ec2",
    name: "EC2",
    category: "compute",
    defaultWidth: 80,
    defaultHeight: 80,
    specFields: [
      { key: "instanceType", label: "インスタンスタイプ", placeholder: "t3.micro" },
      { key: "ami", label: "AMI" },
      { key: "storage", label: "ストレージ" },
      { key: "os", label: "OS" },
    ],
  },
  {
    id: "lambda",
    name: "Lambda",
    category: "compute",
    defaultWidth: 80,
    defaultHeight: 80,
    specFields: [
      { key: "runtime", label: "ランタイム" },
      { key: "memory", label: "メモリ" },
      { key: "timeout", label: "タイムアウト" },
    ],
  },
  { id: "lightsail", name: "Lightsail", category: "compute", defaultWidth: 80, defaultHeight: 80 },
  { id: "batch", name: "Batch", category: "compute", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "elastic-beanstalk",
    name: "Elastic Beanstalk",
    category: "compute",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: "app-runner",
    name: "App Runner",
    category: "compute",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: "ecs",
    name: "ECS",
    category: "container",
    defaultWidth: 80,
    defaultHeight: 80,
    specFields: [
      { key: "launchType", label: "起動タイプ" },
      { key: "cpu", label: "CPU" },
      { key: "memory", label: "メモリ" },
      { key: "desiredCount", label: "タスク数" },
    ],
  },
  {
    id: "ecs-fargate",
    name: "Fargate",
    category: "container",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  { id: "eks", name: "EKS", category: "container", defaultWidth: 80, defaultHeight: 80 },
  { id: "ecr", name: "ECR", category: "container", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "s3",
    name: "S3",
    category: "storage",
    defaultWidth: 80,
    defaultHeight: 80,
    specFields: [
      { key: "storageClass", label: "ストレージクラス" },
      { key: "versioning", label: "バージョニング" },
      { key: "encryption", label: "暗号化" },
    ],
  },
  { id: "efs", name: "EFS", category: "storage", defaultWidth: 80, defaultHeight: 80 },
  { id: "ebs", name: "EBS", category: "storage", defaultWidth: 80, defaultHeight: 80 },
  { id: "glacier", name: "S3 Glacier", category: "storage", defaultWidth: 80, defaultHeight: 80 },
  { id: "backup", name: "Backup", category: "storage", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "storage-gateway",
    name: "Storage Gateway",
    category: "storage",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: "rds",
    name: "RDS",
    category: "database",
    defaultWidth: 80,
    defaultHeight: 80,
    specFields: [
      { key: "engine", label: "エンジン" },
      { key: "instanceClass", label: "インスタンスクラス" },
      { key: "storage", label: "ストレージ" },
      { key: "multiAz", label: "Multi-AZ" },
    ],
  },
  {
    id: "aurora",
    name: "Aurora",
    category: "database",
    defaultWidth: 80,
    defaultHeight: 80,
    specFields: [
      { key: "engine", label: "エンジン" },
      { key: "instanceClass", label: "インスタンスクラス" },
    ],
  },
  { id: "dynamodb", name: "DynamoDB", category: "database", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "elasticache",
    name: "ElastiCache",
    category: "database",
    defaultWidth: 80,
    defaultHeight: 80,
    specFields: [
      { key: "engine", label: "エンジン" },
      { key: "nodeType", label: "ノードタイプ" },
    ],
  },
  { id: "redshift", name: "Redshift", category: "database", defaultWidth: 80, defaultHeight: 80 },
  { id: "neptune", name: "Neptune", category: "database", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "documentdb",
    name: "DocumentDB",
    category: "database",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  { id: "keyspaces", name: "Keyspaces", category: "database", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "timestream",
    name: "Timestream",
    category: "database",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  { id: "vpc", name: "VPC", category: "network", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "alb",
    name: "ALB",
    category: "network",
    defaultWidth: 80,
    defaultHeight: 80,
    specFields: [
      { key: "scheme", label: "スキーム" },
      { key: "listeners", label: "リスナー" },
    ],
  },
  { id: "nlb", name: "NLB", category: "network", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "cloudfront",
    name: "CloudFront",
    category: "network",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  { id: "route53", name: "Route 53", category: "network", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "api-gateway",
    name: "API Gateway",
    category: "network",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: "nat-gateway",
    name: "NAT Gateway",
    category: "network",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: "direct-connect",
    name: "Direct Connect",
    category: "network",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: "global-accelerator",
    name: "Global Accelerator",
    category: "network",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: "transit-gateway",
    name: "Transit Gateway",
    category: "network",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  { id: "sqs", name: "SQS", category: "application", defaultWidth: 80, defaultHeight: 80 },
  { id: "sns", name: "SNS", category: "application", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "eventbridge",
    name: "EventBridge",
    category: "application",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  { id: "ses", name: "SES", category: "application", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "step-functions",
    name: "Step Functions",
    category: "application",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  { id: "appsync", name: "AppSync", category: "application", defaultWidth: 80, defaultHeight: 80 },
  { id: "mq", name: "MQ", category: "application", defaultWidth: 80, defaultHeight: 80 },
  { id: "iam", name: "IAM", category: "security", defaultWidth: 80, defaultHeight: 80 },
  { id: "waf", name: "WAF", category: "security", defaultWidth: 80, defaultHeight: 80 },
  { id: "acm", name: "ACM", category: "security", defaultWidth: 80, defaultHeight: 80 },
  { id: "cognito", name: "Cognito", category: "security", defaultWidth: 80, defaultHeight: 80 },
  { id: "kms", name: "KMS", category: "security", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "secrets-manager",
    name: "Secrets Manager",
    category: "security",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  { id: "shield", name: "Shield", category: "security", defaultWidth: 80, defaultHeight: 80 },
  { id: "guardduty", name: "GuardDuty", category: "security", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "security-hub",
    name: "Security Hub",
    category: "security",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: "cloudwatch",
    name: "CloudWatch",
    category: "management",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: "cloudformation",
    name: "CloudFormation",
    category: "management",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: "ssm",
    name: "Systems Manager",
    category: "management",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: "cloudtrail",
    name: "CloudTrail",
    category: "management",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  { id: "config", name: "Config", category: "management", defaultWidth: 80, defaultHeight: 80 },
  { id: "kinesis", name: "Kinesis", category: "analytics", defaultWidth: 80, defaultHeight: 80 },
  { id: "athena", name: "Athena", category: "analytics", defaultWidth: 80, defaultHeight: 80 },
  { id: "glue", name: "Glue", category: "analytics", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "quicksight",
    name: "QuickSight",
    category: "analytics",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  { id: "msk", name: "MSK", category: "analytics", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "opensearch",
    name: "OpenSearch",
    category: "analytics",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: "codepipeline",
    name: "CodePipeline",
    category: "devtools",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  { id: "codebuild", name: "CodeBuild", category: "devtools", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "codedeploy",
    name: "CodeDeploy",
    category: "devtools",
    defaultWidth: 80,
    defaultHeight: 80,
  },
  { id: "amplify", name: "Amplify", category: "devtools", defaultWidth: 80, defaultHeight: 80 },
  { id: "sagemaker", name: "SageMaker", category: "ai-ml", defaultWidth: 80, defaultHeight: 80 },
  {
    id: "bedrock",
    name: "Bedrock",
    category: "ai-ml",
    defaultWidth: 80,
    defaultHeight: 80,
    specFields: [
      { key: "model", label: "モデル" },
      { key: "throughput", label: "スループット" },
    ],
  },
  { id: "user", name: "User/Client", category: "network", defaultWidth: 80, defaultHeight: 80 },
];

export function getServiceDef(type: string): AwsServiceDef | undefined {
  return AWS_SERVICES.find((s) => s.id === type);
}

export function getServicesByCategory(): Map<string, AwsServiceDef[]> {
  const map = new Map<string, AwsServiceDef[]>();
  for (const service of AWS_SERVICES) {
    const list = map.get(service.category);
    if (list) {
      list.push(service);
    } else {
      map.set(service.category, [service]);
    }
  }
  return map;
}
