name = "mermaid-architecture"
main = "src/worker/index.ts"
compatibility_date = "2025-04-28"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

routes = [
  { pattern = "mermaid-architecture.0g0.xyz", custom_domain = true }
]

[observability]
enabled = true

[vars]
DEV_MODE = "false"
CF_ACCESS_AUD = "134411172b5651e1de7ef0090d88b71ae790a078dea2e8bf17ec59ad3a801c03"
CF_ACCESS_CERTS_URL = "https://0g0.cloudflareaccess.com/cdn-cgi/access/certs"

[site]
bucket = "./dist/client"

[[d1_databases]]
binding = "DB"
database_name = "mermaid-arch-db"
database_id = "386916bc-18f9-4867-91f8-7e5e0df6cd35"
migrations_dir = "migrations"

[durable_objects]
bindings = [
  { name = "DIAGRAM_ROOM", class_name = "DiagramRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["DiagramRoom"]
