export const AWS_ICON_MAP: Record<string, string> = {
  ec2: "logos:aws-ec2",
  lambda: "logos:aws-lambda",
  ecs: "logos:aws-ecs",
  "ecs-fargate": "logos:aws-fargate",
  lightsail: "logos:aws-lightsail",
  s3: "logos:aws-s3",
  efs: "logos:aws",
  ebs: "logos:aws",
  rds: "logos:aws-rds",
  aurora: "logos:aws-aurora",
  dynamodb: "logos:aws-dynamodb",
  elasticache: "logos:aws-elasticache",
  vpc: "logos:aws-vpc",
  alb: "logos:aws-elb",
  nlb: "logos:aws-elb",
  cloudfront: "logos:aws-cloudfront",
  route53: "logos:aws-route53",
  "api-gateway": "logos:aws-api-gateway",
  "nat-gateway": "logos:aws",
  sqs: "logos:aws-sqs",
  sns: "logos:aws-sns",
  eventbridge: "logos:aws-eventbridge",
  ses: "logos:aws-ses",
  iam: "logos:aws-iam",
  waf: "logos:aws-waf",
  acm: "logos:aws-certificate-manager",
  cognito: "logos:aws-cognito",
  cloudwatch: "logos:aws-cloudwatch",
  cloudformation: "logos:aws-cloudformation",
  ssm: "logos:aws-systems-manager",
  kinesis: "logos:aws-kinesis",
  athena: "logos:aws-athena",
  user: "mdi:account",
};

export function getIconName(serviceId: string): string | undefined {
  return AWS_ICON_MAP[serviceId];
}
