import { SERVICE_TO_TERRAFORM } from "./mappings";
import type {
  TerraformGroup,
  TerraformInput,
  TerraformMapping,
  TerraformNode,
  TerraformOptions,
} from "./types";

function sanitizeResourceName(label: string): string {
  return label
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");
}

function findParentGroup(nodeId: string, groups: TerraformGroup[]): TerraformGroup | undefined {
  return groups.find((g) => g.children.includes(nodeId));
}

function resolveNodeLabel(nodeId: string, input: TerraformInput): string {
  const node = input.nodes.find((n) => n.id === nodeId);
  return node ? node.label : nodeId;
}

function buildResourceBlock(
  resourceType: string,
  resourceName: string,
  attrs: { key: string; value: string; isComment?: boolean }[],
  tagName: string,
  groupComment?: string,
): string {
  const lines: string[] = [];
  if (groupComment) {
    lines.push(groupComment);
  }
  lines.push(`resource "${resourceType}" "${resourceName}" {`);
  for (const attr of attrs) {
    if (attr.isComment) {
      lines.push(`  # ${attr.key} = ${attr.value}`);
    } else {
      lines.push(`  ${attr.key} = "${attr.value}"`);
    }
  }
  lines.push("  tags = {");
  lines.push(`    Name = "${tagName}"`);
  lines.push("  }");
  lines.push("}");
  return lines.join("\n");
}

function deduplicateResourceNames(
  entries: { resourceType: string; resourceName: string }[],
): Map<number, string> {
  const nameCount = new Map<string, number>();
  const result = new Map<number, string>();

  for (let i = 0; i < entries.length; i++) {
    const key = `${entries[i].resourceType}:${entries[i].resourceName}`;
    const count = nameCount.get(key) ?? 0;
    nameCount.set(key, count + 1);
  }

  const nameUsed = new Map<string, number>();
  for (let i = 0; i < entries.length; i++) {
    const key = `${entries[i].resourceType}:${entries[i].resourceName}`;
    const total = nameCount.get(key)!;
    if (total === 1) {
      result.set(i, entries[i].resourceName);
    } else {
      const used = nameUsed.get(key) ?? 0;
      nameUsed.set(key, used + 1);
      result.set(
        i,
        used === 0 ? entries[i].resourceName : `${entries[i].resourceName}_${used + 1}`,
      );
    }
  }

  return result;
}

export function generateTerraform(input: TerraformInput, options: TerraformOptions = {}): string {
  const region = options.region ?? "ap-northeast-1";
  const providerVersion = options.providerVersion ?? "~> 5.0";
  const labelResolver = options.serviceLabelResolver ?? (() => undefined);

  const lines: string[] = [];

  lines.push("# ============================================================");
  lines.push("# Terraform / OpenTofu 構成ファイル");
  lines.push("# Generated by Mermaid Architecture");
  lines.push("# ============================================================");
  lines.push("");
  lines.push("terraform {");
  lines.push("  required_providers {");
  lines.push("    aws = {");
  lines.push(`      source  = "hashicorp/aws"`);
  lines.push(`      version = "${providerVersion}"`);
  lines.push("    }");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push('provider "aws" {');
  lines.push(`  region = "${region}"`);
  lines.push("}");

  const vpcGroups = input.groups.filter((g) => g.type === "vpc");
  const subnetGroups = input.groups.filter((g) => g.type === "subnet");
  const otherGroups = input.groups.filter((g) => g.type !== "vpc" && g.type !== "subnet");

  if (vpcGroups.length > 0 || subnetGroups.length > 0) {
    lines.push("");
    lines.push("# ------------------------------------------------------------");
    lines.push("# VPC / ネットワーク");
    lines.push("# ------------------------------------------------------------");

    for (const vpc of vpcGroups) {
      const name = sanitizeResourceName(vpc.label) || "main_vpc";
      lines.push(`resource "aws_vpc" "${name}" {`);
      lines.push('  cidr_block = "10.0.0.0/16"');
      lines.push("  tags = {");
      lines.push(`    Name = "${vpc.label}"`);
      lines.push("  }");
      lines.push("}");
    }

    for (const subnet of subnetGroups) {
      const name = sanitizeResourceName(subnet.label) || "main_subnet";
      const parentVpc = input.groups.find(
        (g) => g.type === "vpc" && g.children.includes(subnet.id),
      );
      lines.push("");
      lines.push(`resource "aws_subnet" "${name}" {`);
      if (parentVpc) {
        const vpcName = sanitizeResourceName(parentVpc.label) || "main_vpc";
        lines.push(`  vpc_id     = aws_vpc.${vpcName}.id`);
      } else {
        lines.push("  # vpc_id = <VPC IDを指定してください>");
      }
      lines.push('  cidr_block = "10.0.1.0/24"');
      lines.push("  tags = {");
      lines.push(`    Name = "${subnet.label}"`);
      lines.push("  }");
      lines.push("}");
    }
  }

  for (const group of otherGroups) {
    lines.push("");
    lines.push(`# --- ${group.label} (${group.type}) ---`);
  }

  const supportedNodes: {
    node: TerraformNode;
    mapping: TerraformMapping;
    resourceType: string;
    resourceName: string;
  }[] = [];
  const unsupportedNodes: TerraformNode[] = [];

  for (const node of input.nodes) {
    const mapping = SERVICE_TO_TERRAFORM[node.type];
    if (mapping) {
      const resourceName = sanitizeResourceName(node.label) || node.type;
      supportedNodes.push({
        node,
        mapping,
        resourceType: mapping.resource,
        resourceName,
      });
    } else {
      unsupportedNodes.push(node);
    }
  }

  const deduped = deduplicateResourceNames(
    supportedNodes.map((e) => ({
      resourceType: e.resourceType,
      resourceName: e.resourceName,
    })),
  );

  if (supportedNodes.length > 0) {
    lines.push("");
    lines.push("# ------------------------------------------------------------");
    lines.push("# リソース");
    lines.push("# ------------------------------------------------------------");

    for (let i = 0; i < supportedNodes.length; i++) {
      const { node, mapping } = supportedNodes[i];
      const finalName = deduped.get(i)!;
      const attrs: { key: string; value: string; isComment?: boolean }[] = [];

      if (mapping.extraAttrs) {
        for (const [key, value] of Object.entries(mapping.extraAttrs)) {
          attrs.push({ key, value });
        }
      }

      if (node.specs) {
        for (const [specKey, specValue] of Object.entries(node.specs)) {
          if (specValue === "") continue;
          const tfKey = mapping.specMap[specKey];
          if (tfKey) {
            attrs.push({ key: tfKey, value: specValue });
          } else {
            attrs.push({ key: specKey, value: specValue, isComment: true });
          }
        }
      }

      const parentGroup = findParentGroup(node.id, input.groups);
      let groupComment: string | undefined;
      if (parentGroup) {
        groupComment = `# ${parentGroup.label} (${parentGroup.type}) 内`;
      }

      lines.push("");
      lines.push(buildResourceBlock(mapping.resource, finalName, attrs, node.label, groupComment));
    }
  }

  if (unsupportedNodes.length > 0) {
    lines.push("");
    lines.push("# ------------------------------------------------------------");
    lines.push("# 未対応リソース");
    lines.push("# ------------------------------------------------------------");
    for (const node of unsupportedNodes) {
      const resolvedName = labelResolver(node.type) ?? node.type;
      lines.push(`# 未対応: ${resolvedName} (${node.type})`);
      lines.push("# TODO: 手動でリソースを追加してください");
    }
  }

  if (input.edges.length > 0) {
    lines.push("");
    lines.push("# ------------------------------------------------------------");
    lines.push("# 接続関係");
    lines.push("# ------------------------------------------------------------");
    for (const edge of input.edges) {
      const sourceLabel = sanitizeResourceName(resolveNodeLabel(edge.source, input));
      const targetLabel = sanitizeResourceName(resolveNodeLabel(edge.target, input));
      const label = edge.label ? ` (${edge.label})` : "";
      lines.push(`# ${sourceLabel} --> ${targetLabel}${label}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}
